replicaCount: 1

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-production

jaeger:
  collector_host: dns:///jaeger-production-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/test-connector
  pullPolicy: Always
  tag: "latest"
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  grpc:
    port: 5101
  metrics:
    port: 60001
  healthchecks:
    port: 60000

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: tc.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: happytravel-tls
      hosts:
        - tc.happytravel.com

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 250Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - test-connector
      topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: true
  podMonitor:
    enabled: true

env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Production"
  HTDC_VAULT_ENDPOINT: "https://vault.happytravel.com/v1/"
  HTDC_TEST_CONNECTOR_SENTRY_ENDPOINT: "https://ed8ee25f965e47a588434752259cb6ce@sentry1.happytravel.com/67"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  HTDC_WEBAPI_PORT: "80"
  HTDC_GRPC_PORT: "5101"
  HTDC_HEALTH_PORT: "60000"
  HTDC_METRICS_PORT: "60001"
  HTDC_REDIS_HOST: "redis-test-connector"
  CONSUL_HTTP_ADDR: "https://consul.happytravel.com/"